#!/bin/bash
action=$1

if [[ "$action" == "-up" ]]
then
	pamixer -i 5
	kill -44 $(pidof dwmblocks)
elif [[ "$action" == "-down" ]]
then
	pamixer -d 5
	kill -44 $(pidof dwmblocks)
elif [[ "$action" == "-mute" ]]
then
	pamixer -t
	kill -44 $(pidof dwmblocks)
else
	echo "usage: set-volume [-up | -down | -mute]"
fi

# /home/sairaj/.dwm/scripts/statusbarf -update
